"""rtpkit.model — Immutable data structures for RTP/RTCP packets and captures."""

from .errors import (
    CaptureError,
    PcapBufferTooShort,
    PcapInvalidMagic,
    PcapngBufferTooShort,
    PcapngInvalidByteOrderMagic,
    PcapngMalformedBlock,
    PcapTruncatedRecord,
    RtcpBufferTooShort,
    RtcpError,
    RtcpInvalidVersion,
    RtcpLengthMismatch,
    RtcpMalformedPacket,
    RtpBufferTooShort,
    RtpBuildError,
    RtpError,
    RtpExtensionError,
    RtpInvalidVersion,
    RtpPaddingError,
)
from .extension import (
    ExtensionElement,
    ExtensionProfile,
    HeaderExtension,
    build_header_extension,
    parse_extension_elements,
)
from .net import DecapsulatedUdp
from .packet import RtpPacket
from .payload_types import DYNAMIC_PAYLOAD_TYPE_RANGE, MediaType, PayloadTypeInfo, lookup_payload_type
from .pcap import PcapPacket
from .rtcp import (
    ApplicationDefined,
    Goodbye,
    ReceiverReport,
    ReportBlock,
    RtcpPacket,
    RtcpPacketType,
    SdesChunk,
    SdesItem,
    SdesItemType,
    SenderInfo,
    SenderReport,
    SourceDescription,
)
from .stream import RtpStreamStats

__all__ = [
    "RtpPacket",
    "HeaderExtension",
    "ExtensionElement",
    "ExtensionProfile",
    "parse_extension_elements",
    "build_header_extension",
    "RtcpPacket",
    "RtcpPacketType",
    "SdesItemType",
    "SenderInfo",
    "ReportBlock",
    "SdesItem",
    "SdesChunk",
    "SenderReport",
    "ReceiverReport",
    "SourceDescription",
    "Goodbye",
    "ApplicationDefined",
    "PcapPacket",
    "DecapsulatedUdp",
    "RtpStreamStats",
    "MediaType",
    "PayloadTypeInfo",
    "lookup_payload_type",
    "DYNAMIC_PAYLOAD_TYPE_RANGE",
    "RtpError",
    "RtpBufferTooShort",
    "RtpInvalidVersion",
    "RtpPaddingError",
    "RtpExtensionError",
    "RtpBuildError",
    "RtcpError",
    "RtcpBufferTooShort",
    "RtcpInvalidVersion",
    "RtcpLengthMismatch",
    "RtcpMalformedPacket",
    "CaptureError",
    "PcapBufferTooShort",
    "PcapInvalidMagic",
    "PcapTruncatedRecord",
    "PcapngBufferTooShort",
    "PcapngInvalidByteOrderMagic",
    "PcapngMalformedBlock",
]
